// The tool's colours: one neutral scale for the chrome, amber and red for warnings and errors, and the region colours.
//
//   node palette.mjs           print the scales and the WCAG contrast audit (exit code 1 if a pair fails)
//   node palette.mjs --write   also rewrite the token block in ../../stocking/static/style.css and PALETTE in
//                              ../../stocking/document.py
//
// The chrome has no hue of its own: the painting and the region colours are the only colour on screen, so skin and
// stocking colours read true. Region colours share one lightness band, so no region shouts louder than another on
// the painting.
import chroma from 'chroma-js';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

// 11 steps; the base lands exactly on index `at`; `darkL` is the lightness of 950.
function scaleFor(base, at = 5, darkL = 0.25) {
  const [, c, h] = chroma(base).oklch();
  const hh = Number.isNaN(h) ? 0 : h;
  const light = chroma.oklch(0.97, Math.min(c || 0, 0.02), hh);
  const dark = chroma.oklch(darkL, Math.min(c || 0, 0.06), hh);
  const lo = chroma.scale([light, base]).mode('oklch').correctLightness().colors(at + 1);
  const hi = chroma.scale([base, dark]).mode('oklch').correctLightness().colors(11 - at).slice(1);
  return Object.fromEntries([...lo, ...hi].map((c, i) => [STEPS[i], c]));
}

const scales = {
  grey: scaleFor(chroma.oklch(0.6, 0, 0), 5, 0.215),
  amber: scaleFor('#e9a23b', 4),
  red: scaleFor('#e5534b', 5),
};

// In the old order (blue, orange, violet, green, yellow, ...) so returning users keep their bearings. Yellow sits
// above the band: at the band's lightness it turns olive.
const REGION_HUES = [
  ['蓝', 255, 0.72, 0.14], ['橙', 50, 0.72, 0.16], ['紫', 305, 0.70, 0.17], ['绿', 165, 0.74, 0.13],
  ['黄', 88, 0.84, 0.15], ['粉', 355, 0.72, 0.16], ['青', 215, 0.78, 0.11], ['草绿', 130, 0.78, 0.15],
  ['红', 25, 0.66, 0.18], ['驼', 70, 0.72, 0.07],
];
const regions = REGION_HUES.map(([name, h, l, c]) => ({ name, hex: chroma.oklch(l, c, h).hex() }));

const roles = {
  chrome: ['grey', 900, 'bar, side panel, status bar'],
  stage: ['grey', 700, 'around the painting: neutral, so colours read true'],
  raised: ['grey', 800, 'buttons, the selected region row: fill, no outline'],
  hover: ['grey', 700, 'a button under the pointer'],
  line: ['grey', 800, 'the few hairlines'],
  text: ['grey', 100, 'body text; the only text colour on the stage'],
  muted: ['grey', 400, 'secondary text on the panel, never on the stage'],
  'muted-raised': ['grey', 300, 'secondary text on a button'],
  faint: ['grey', 600, 'disabled; the other step\'s numeral'],
  chalk: ['grey', 50, 'selected mode, style, zoom; focus ring'],
  primary: ['grey', 100, 'the main action (导出): one step below chalk, so hovering can brighten it'],
  'primary-hover': ['grey', 50, 'the main action under the pointer: brighter, more contrast'],
  'on-chalk': ['grey', 950, 'text on chalk and on region colours'],
  float: ['grey', 950, 'menus and bars over the painting'],
  warn: ['amber', 300, 'warnings'],
  error: ['red', 300, 'errors, 删除'],
};
const role = (k) => scales[roles[k][0]][roles[k][1]];

const audits = [
  ['text', 'chrome', 4.5], ['muted', 'chrome', 4.5], ['text', 'raised', 4.5], ['muted-raised', 'raised', 4.5],
  ['text', 'hover', 4.5], ['on-chalk', 'chalk', 4.5], ['text', 'stage', 4.5], ['text', 'float', 4.5],
  ['muted', 'float', 4.5], ['chalk', 'chrome', 3], ['chalk', 'raised', 3], ['warn', 'chrome', 4.5],
  ['warn', 'stage', 3], ['error', 'chrome', 4.5], ['error', 'float', 4.5], ['on-chalk', 'primary', 4.5],
  ['on-chalk', 'primary-hover', 4.5], ['primary', 'chrome', 3],
].map(([f, b, min]) => [`${f} on ${b}`, role(f), role(b), min]);
audits.push(['raised on chrome (visible)', role('raised'), role('chrome'), 1.3]);
for (const r of regions) {
  audits.push([`region ${r.name} on chrome`, r.hex, role('chrome'), 3]);
  audits.push([`region ${r.name} on raised`, r.hex, role('raised'), 3]);
  audits.push([`on-chalk on region ${r.name}`, role('on-chalk'), r.hex, 4.5]);
}

let fails = 0;
for (const [name, s] of Object.entries(scales)) console.log(name.padEnd(6), STEPS.map((k) => `${k} ${s[k]}`).join('  '));
console.log('region', regions.map((r) => r.hex).join(' '));
console.log('\ncontrast (WCAG 2):');
for (const [name, fg, bg, min] of audits) {
  const ratio = chroma.contrast(fg, bg);
  if (ratio < min) fails++;
  console.log(`  ${ratio >= min ? 'pass' : 'FAIL'} ${ratio.toFixed(2).padStart(5)} >= ${min}  ${name}`);
}
console.log(`${fails} failing`);

if (process.argv.includes('--write')) {
  const cssPath = fileURLToPath(new URL('../../stocking/static/style.css', import.meta.url));
  const block = ['  /* palette:start (generated by tools/palette/palette.mjs: edit there and run it with --write) */'];
  for (const [name, s] of Object.entries(scales)) for (const k of STEPS) block.push(`  --${name}-${k}: ${s[k]};`);
  for (const [k, [scale, step, why]] of Object.entries(roles)) {
    const decl = `  --${k}: var(--${scale}-${step});`;
    block.push(`${decl.padEnd(34)}/* ${why} */`);
  }
  block.push('  /* palette:end */');
  const css = readFileSync(cssPath, 'utf8');
  const nlc = css.includes('\r\n') ? '\r\n' : '\n';
  const re = /  \/\* palette:start[\s\S]*?palette:end \*\//;
  if (!re.test(css)) throw new Error('style.css has no palette:start ... palette:end block');
  writeFileSync(cssPath, css.replace(re, block.join(nlc)));
  const pyPath = fileURLToPath(new URL('../../stocking/document.py', import.meta.url));
  const py = readFileSync(pyPath, 'utf8');
  const nlp = py.includes('\r\n') ? '\r\n' : '\n';
  const hex = regions.map((r) => `'${r.hex}'`);
  const line = `PALETTE = (${hex.slice(0, 5).join(', ')},${nlp}           ${hex.slice(5).join(', ')})`;
  if (!/PALETTE = \([^)]*\)/.test(py)) throw new Error('document.py has no PALETTE');
  writeFileSync(pyPath, py.replace(/PALETTE = \([^)]*\)/, line));
  console.log('wrote the tokens in style.css and PALETTE in document.py');
}
process.exitCode = fails ? 1 : 0;
